"""Reset state and re-submit all 8 city orders using verified data from previous run."""
import json
import os

import requests
from dotenv import load_dotenv

load_dotenv()

HUB_URL = os.environ["HUB_URL"].rstrip("/")
HUB_API_KEY = os.environ["HUB_API_KEY"]


def call_api(answer: dict) -> dict:
    payload = {"apikey": HUB_API_KEY, "task": "foodwarehouse", "answer": answer}
    print(f"→ {json.dumps(answer, ensure_ascii=False)}")
    resp = requests.post(f"{HUB_URL}/verify", json=payload, timeout=30)
    result = resp.json()
    print(f"← {json.dumps(result, ensure_ascii=False)}")
    return result


def items_list(items_dict: dict) -> list:
    """Convert {name: quantity} to [{"name": name, "items": quantity}]."""
    return [{"name": k, "items": v} for k, v in items_dict.items()]


# All data verified from previous agent run.
# creatorID=2 = tgajewski (birthday=1991-04-06, role=2/transport)
# Signatures generated by signatureGenerator for each destination.
ORDERS = [
    {
        "title": "Order for Opalino",
        "creatorID": 2,
        "destination": 991828,
        "signature": "96d66cc4d28484b3c5b9e05e4f79152eb564f6e0",
        "items": {"chleb": 45, "woda": 120, "mlotek": 6},
    },
    {
        "title": "Order for Domatowo",
        "creatorID": 2,
        "destination": 761834,
        "signature": "29361bec85afce60df2f3472af1a6e298154e82f",
        "items": {"makaron": 60, "woda": 150, "lopata": 8},
    },
    {
        "title": "Order for Brudzewo",
        "creatorID": 2,
        "destination": 234434,
        "signature": "5d1db416d5a978fa56e9610c3598d821492acaeb",
        "items": {"ryz": 55, "woda": 140, "wiertarka": 5},
    },
    {
        "title": "Order for Darzlubie",
        "creatorID": 2,
        "destination": 676323,
        "signature": "9c52ae1ab999cfc3b26762dcadcdb2407c5fbde6",
        "items": {"wolowina": 25, "woda": 130, "kilof": 7},
    },
    {
        "title": "Order for Celbowo",
        "creatorID": 2,
        "destination": 741906,
        "signature": "d539fbc8eeee8093f9def9e8d2c39e764de1b704",
        "items": {"kurczak": 40, "woda": 125, "mlotek": 6},
    },
    {
        "title": "Order for Mechowo",
        "creatorID": 2,
        "destination": 695992,
        "signature": "8d75eb210a3d5e80098bd6900d10f9e9791069d2",
        "items": {"ziemniaki": 100, "kapusta": 70, "marchew": 65, "woda": 165, "lopata": 9},
    },
    {
        "title": "Order for Puck",
        "creatorID": 2,
        "destination": 140606,
        "signature": "414ab8e00fdfc2697876ea4a6db098edc38a0c60",
        "items": {"chleb": 50, "ryz": 45, "woda": 175, "wiertarka": 7},
    },
    {
        "title": "Order for Karlinkowo",
        "creatorID": 2,
        "destination": 707536,
        "signature": "534a7ff14801f6bc8614ba92b43b81f92a9222a3",
        "items": {"makaron": 52, "wolowina": 22, "ziemniaki": 95, "woda": 155, "kilof": 6},
    },
]


def main():
    # Step 1: reset
    print("\n=== RESET ===")
    call_api({"tool": "reset"})

    # Step 2: create and fill each order sequentially
    for order in ORDERS:
        print(f"\n=== {order['title']} ===")
        result = call_api({
            "tool": "orders",
            "action": "create",
            "title": order["title"],
            "creatorID": order["creatorID"],
            "destination": order["destination"],
            "signature": order["signature"],
        })
        if result.get("code") != 110:
            print(f"  ERROR creating order: {result}")
            return

        order_id = result["order"]["id"]
        append_result = call_api({
            "tool": "orders",
            "action": "append",
            "id": order_id,
            "items": items_list(order["items"]),
        })
        if append_result.get("code") != 120:
            print(f"  ERROR appending items: {append_result}")
            return

    # Step 3: done
    print("\n=== DONE ===")
    call_api({"tool": "done"})


if __name__ == "__main__":
    main()
